### ISSUE TITLE
Provide a way to send a .torrent to a transmission webserver

### ISSUE THREAD

**Issue by almet** [stuxo/REDAndroid#9]
It could be handy to have this option, what do you think?

**Comment by stuxo** [comment]
Why transmission and not others? I chose to support wm and pywhatauto first because I think that gives good coverage, especially given the demographic of people using this app. I'm worried if we support specific clients, we will need to support them all. We can do this, but I'm not sure it's the correct approach.

**Comment by almet** [comment]
That actually seems correct: I've configured my android client to support .torrent files with an app that uploads them to my server, that should be enough.
